### PR TITLE
Add a makefile compatible with z/OS make

### PR DESCRIPTION
**Pull request by ifakhrutdinov**

### CODE REVIEW

**Comment by jackjia-ibm** [comment]
Thanks @ifakhrutdinov. I did a quick test, and the make step still failed with an error:

```
+ make -f zosMakefile 
make: Error -- FSUM9415 Don't know how to make CEE.SCEELKED:SYS1.CSSLIB:CSF.SCSFMOD0
```

You can see the test build here: https://wash.zowe.org:8443/view/Zowe/job/zowe-launcher/job/users%252Fjack%252Ftest-makefile/2/console. Could you pls take a look? Thanks!

**Comment by ifakhrutdinov** [comment]
@jackjia-ibm you may have to explicitly specify a target
```
make -f zosMakefile all
make -f zosMakefile clean
```
Meanwhile I'll have a look if it's possible to have a default one with this version of make.

**Comment by ifakhrutdinov** [comment]
@jackjia-ibm, actually, I don't think we need that export. Please try running without any targets.

**Comment by jackjia-ibm** [comment]
Thanks @ifakhrutdinov. I did another try and here is what I found:

```
ZOWEAD7:/ZOWE/tmp/launcher: >make -f zosMakefile all
xlclang -O -D_OPEN_THREADS -D_XOPEN_SOURCE=600  "-Wa,goff" -Wall -Wextra -Werror -pedantic  -Wno-gnu-zero-variadic-macro-arguments  -Wno-missing-braces  -Wno-missing-field-initializers  -Wno-unused-parameter  "-Wc,langlvl(EXTC99),float(HEX),agg,list(),so(),search(),lp64,xplink"  "-Wc,goff,xref,gonum,roconst,gonum,asm,asmlib('SYS1.MACLIB'),asmlib('CEE.SCEEMAC')"  -I . -o main.o -c src/main.c
FSUM3224 xlclang: Fatal error in /usr/lpp/cbclib/xlclang/exe/clcdrvr: signal 9 received.
FSUM8226 make: Error code 251 
ZOWEAD7:/ZOWE/tmp/launcher: >ls -l /usr/lpp/cbclib/xlclang/exe
total 16
erwxrwxrwx   1 OMVSKERN OMVSGRP        7 Mar  6  2019 clcdrvr -> CLCDRVR
drwxr-xr-x   2 OMVSKERN OMVSGRP     8192 Mar  6  2019 default_msg
ZOWEAD7:/ZOWE/tmp/launcher: >cat /usr/lpp/cbclib/xlclang/etc/xlclang.cfg
*
* FUNCTION: z/OS 2R3M1 XL C/C++ Compiler Configuration file
*
* Licensed Materials - Property of IBM
* 5650-ZOS Copyright IBM Corp. 2019.
* US Government Users Restricted Rights - Use, duplication or
* disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*

* Clang C compiler
clang:        use               = DEFLT
              cinc              = -isystem/usr/include/le
              libraries         = -L/usr/lpp/cbclib/lib,-libmcmp

* Clang C++ compiler
clang++:      use               = DEFLT
              options           = -D_XOPEN_SOURCE=600,-D_UNIX03_WITHDRAWN,-D__static_assert=static_assert,-Wno-parentheses,-Wno-unused-value
              cinc              = -isystem/usr/include/le
              cppinc            = -isystem/usr/include/c++,-isystem/usr/include/le
              libraries         = -L/usr/lpp/cbclib/lib,-libmcmp

* common definitions
DEFLT:        cppcomp           = /usr/lpp/cbclib/xlclang/exe/clcdrvr
              ccomp             = /usr/lpp/cbclib/xlclang/exe/clcdrvr
              ipacomp           = /usr/lpp/cbclib/xlclang/exe/clcdrvr
              ld_c              = /bin/c89
              ld_cpp            = /bin/cxx
              xlC               = /usr/lpp/cbclib/xlclang/bin/xlclang
              xlCcopt           = -D_XOPEN_SOURCE
              sysobj            = cee.sceeobj:cee.sceecpp
              syslib_x          = cee.sceebnd2:sys1.csslib
              exportlist_c      = NONE
              exportlist_c_x    = cee.sceelib(celhs003,celhs001)
              exportlist_cpp_x  = cee.sceelib(celhs003,celhs001,celhscpp)
              exportlist_c_64   = cee.sceelib(celqs003)
              exportlist_cpp_64 = cee.sceelib(celqs003,celqscpp,cxxrt64)
              steplib           = cbc.sclccmp
```

I think the problem is steplib `cbc.sclccmp` doesn't exists on Marist system. I checked `xlc` does seems configured ok, the steplib and cppcomp/ccomp/ipacomp entries all exist. I tried to change Makefile to use `xlc`, removed some warnings on `-W` options, and got this error which I don't quite understand:

```
ZOWEAD7:/ZOWE/tmp/launcher: >make -f zosMakefile
mkdir -p bin
xlc -o bin/zowe_launcher main.o || { rm bin/zowe_launcher; exit 1; }
 IEW2469E 9907 THE ATTRIBUTES OF A REFERENCE TO pthread_mutex_init FROM SECTION 
          main#C DO NOT MATCH THE ATTRIBUTES OF THE TARGET SYMBOL. REASON  2    
 IEW2469E 9907 THE ATTRIBUTES OF A REFERENCE TO pthread_cond_init FROM SECTION  
          main#C DO NOT MATCH THE ATTRIBUTES OF THE TARGET SYMBOL. REASON  2    
 IEW2469E 9907 THE ATTRIBUTES OF A REFERENCE TO chdir FROM SECTION main#C DO NOT
          MATCH THE ATTRIBUTES OF THE TARGET SYMBOL. REASON  2                  
...
 IEW2470E 9511 ORDERED SECTION CEESTART NOT FOUND IN MODULE.                    
 IEW2648E 5111 ENTRY CEESTART IS NOT A CSECT OR AN EXTERNAL NAME IN THE MODULE. 
FSUM3065 The LINKEDIT step ended with return code 8.
FSUM8226 make: Error code 1 
```

There are many lines of `IEW2469E` errors. Does that mean the `main.c` is not compatible with XL C++ compiler?

**Comment by ifakhrutdinov** [comment]
@jackjia-ibm if the library exists, it's probably not APF-authorized. See https://www.ibm.com/support/pages/apar/OA51139. 

```
Local fix

    BYPASS/CIRCUMVENTION:
    Add the library, where the LOAD module pointed by the external
    link resides, to the APF list
```
If it doesn't exist, can you or anyone else deploy it?

**Review by jackjia-ibm — APPROVED** [review]
Yeah build passed.

**Pull request merged**
