### PR TITLE
Fix in environment variable handling

### PR DESCRIPTION
**Pull request by pablocarle**
- Fix memory allocation for environment variable handling
- Add debugging logs

### CODE REVIEW

**Comment by ifakhrutdinov** [comment]
@pablocarle you have a commit with text "wip", is it ready to be reviewed? Could you squash and add a description of what's being done to the commit?

**Comment by ifakhrutdinov** [comment]
FYI, here's a good post about that: https://cbea.ms/git-commit/

Not saying my messages are always ideal, but it's good to try to have clearer commit messages :-)

**Comment by pablocarle** [comment]
@ifakhrutdinov Hi Irek, it's just me not knowing the contribution guidelines for this repository, we are used to make many commits to the PR and then squashing when going to the base branch.
But I can squash them and change the message, not a problem

**Comment by pablocarle** [comment]
I think it will be easier to just open a new PR. I'm actually not sure how to squash them before merging the PR

**Pull request closed without merging**
